### ISSUE TITLE
support select sql

### ISSUE THREAD

**Issue by cmdares** [ClickHouse/clickhouse-jdbc-bridge#16] opened 2019-12-13 05:44 UTC
support
SELECT * FROM jdbc('jdbc:xx','xxx','select a,b,c from xxx where a>0 and rownum<1000')
Note the escape of the quote

**Comment by ramazanpolat** [comment] 2019-12-23 12:01
Why not use this?
```sql
SELECT a,b,c 
FROM jdbc('jdbc:xx','schema', 'table')
WHERE a > 0 nad rownum<1000
```

**Comment by alex-krash** [comment] 2019-12-23 12:38
> support
> SELECT * FROM jdbc('jdbc:xx','xxx','select a,b,c from xxx where a>0 and rownum<1000')
> Note the escape of the quote

Such change will break compatibility with existing odbc function.

**Comment by zhicwu** [comment] 2020-11-29 03:36
This was not working as only table is supported by design. Fortunately there's a workaround to make adhoc query working. Check out adhoc/saved/named query on master branch, which I believe is what you need.

I'll close this once 2.0 is released in December.

**Closed** 2021-01-15 22:58 UTC
Labels: enhancement
